services:
  ecommercedb:
    build:
      context: ./db
    image: revelation6991/ecommerce-db
    container_name: ecommercedb
    ports:
      - "3306:3306"
    volumes:
      - ecommercedbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ecommerce_root_pass
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=ecommerce_user
      - MYSQL_PASSWORD=ecommerce_user_pass

  ecommerceapp:
    build:
      context: ./app
    image: revelation6991/ecommerce-app
    container_name: ecommerceapp
    ports:
      - "9000:9000"
    volumes:
      # Mount local web files into the container
      - ./Ecommerce-app-h:/var/www/html
    depends_on:
      - ecommercedb

  ecommerceweb:
    build:
      context: ./web
    image: revelation6991/ecommerce-web
    container_name: ecommerceweb
    ports:
      - "8080:80"
    volumes:
      # Ensure this matches the runtime location of web files
      - ./Ecommerce-app-h:/var/www/html
    depends_on:
      - ecommerceapp

volumes:
  ecommercedbdata

